engines:
  eslint:
    enabled: true
    channel: 'eslint-9'
    config:
      config: 'eslint.config.mjs'

checks:
  method-complexity:
    config:
      threshold: 10

ratings:
  paths:
    - '**.js'
