name: Tests

on: [ push ]

env:
  CI: true

jobs:

  ci-test:

    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 12, 14, 16]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v2
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install

    - name: Test
      run: npm run test
