on: [ pull_request ]

name: Test Coverage

jobs:

  coverage:
    name: Codecov
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      name: Checkout Code
      with:
        fetch-depth: 1

    - name: Use Node.js 12
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Install
      run: |
        npm install
        npm install --no-save nyc codecov

    - name: Run Coverage
      run: npm run cover

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
